// <auto-generated />
using System;
using FM.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FM.Data.Migrations
{
    [DbContext(typeof(FMDbContext))]
    partial class FMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FM.Data.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Premier"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Primera"
                        });
                });

            modelBuilder.Entity("FM.Data.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int?>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasFilter("[TeamId] IS NOT NULL");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Hristo",
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Petar",
                            LastName = "Botev",
                            Nationality = "Bulgarian",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Dimitar",
                            LastName = "Georgiev",
                            Nationality = "Bulgarian",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Nasko",
                            LastName = "Sirakov",
                            Nationality = "Bulgarian",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Hristo",
                            LastName = "Stoichkov",
                            Nationality = "Bulgarian",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Dimitar",
                            LastName = "Dimitrov",
                            Nationality = "Bulgarian",
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("FM.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayTeamGoals");

                    b.Property<int>("AwayTeamId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HomeTeamGoals");

                    b.Property<int>("HomeTeamId");

                    b.Property<bool>("IsMatchPlayed");

                    b.Property<int>("LeagueId");

                    b.Property<int>("StadiumId");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FM.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("PositionId");

                    b.Property<decimal>("Price");

                    b.Property<int>("Rating");

                    b.Property<int?>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Dimitar",
                            IsDeleted = false,
                            LastName = "Georgiev",
                            Nationality = "Bulgarian",
                            PositionId = 1,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Hristo",
                            IsDeleted = false,
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Todor",
                            IsDeleted = false,
                            LastName = "Todorov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 800000m,
                            Rating = 80,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Yordan",
                            IsDeleted = false,
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Cvetan",
                            IsDeleted = false,
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Borislav",
                            IsDeleted = false,
                            LastName = "Stoimenov",
                            Nationality = "Bulgarian",
                            PositionId = 4,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Petar",
                            IsDeleted = false,
                            LastName = "Botev",
                            Nationality = "Bulgarian",
                            PositionId = 4,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Stefan",
                            IsDeleted = false,
                            LastName = "Georgiev",
                            Nationality = "Bulgarian",
                            PositionId = 1,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Teodor",
                            IsDeleted = false,
                            LastName = "Todorov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 800000m,
                            Rating = 80,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Kiril",
                            IsDeleted = false,
                            LastName = "Konov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 850000m,
                            Rating = 85,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Tedi",
                            IsDeleted = false,
                            LastName = "Salparov",
                            Nationality = "Bulgarian",
                            PositionId = 1,
                            Price = 700000m,
                            Rating = 70,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Shefket",
                            IsDeleted = false,
                            LastName = "Islqmov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 700000m,
                            Rating = 70,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Tihomir",
                            IsDeleted = false,
                            LastName = "Todorov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 840000m,
                            Rating = 84,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Kiril",
                            IsDeleted = false,
                            LastName = "Stanoev",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Nikolay",
                            IsDeleted = false,
                            LastName = "Tenev",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 740000m,
                            Rating = 74,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Stefan",
                            IsDeleted = false,
                            LastName = "Yordanov",
                            Nationality = "Bulgarian",
                            PositionId = 4,
                            Price = 910000m,
                            Rating = 91,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Dimitar",
                            IsDeleted = false,
                            LastName = "Ivankov",
                            Nationality = "Bulgarian",
                            PositionId = 1,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Stanimir",
                            IsDeleted = false,
                            LastName = "Stoilov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 740000m,
                            Rating = 74,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Filip",
                            IsDeleted = false,
                            LastName = "Todorov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 700000m,
                            Rating = 70,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Ivo",
                            IsDeleted = false,
                            LastName = "Dilov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 400000m,
                            Rating = 40,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Dimitar",
                            IsDeleted = false,
                            LastName = "Mihov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Ivanov",
                            Nationality = "Bulgarian",
                            PositionId = 4,
                            Price = 950000m,
                            Rating = 95,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Teodosii",
                            IsDeleted = false,
                            LastName = "Ivankov",
                            Nationality = "Bulgarian",
                            PositionId = 1,
                            Price = 500000m,
                            Rating = 50,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Bodurov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 650000m,
                            Rating = 65,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Daniel",
                            IsDeleted = false,
                            LastName = "Petrov",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 400000m,
                            Rating = 40,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Todorov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 600000m,
                            Rating = 60,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Valentin",
                            IsDeleted = false,
                            LastName = "Yordanov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 1000000m,
                            Rating = 100,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Mladen",
                            IsDeleted = false,
                            LastName = "Yordanov",
                            Nationality = "Bulgarian",
                            PositionId = 4,
                            Price = 950000m,
                            Rating = 95,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Kirqkov",
                            Nationality = "Bulgarian",
                            PositionId = 1,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Kozmin",
                            IsDeleted = false,
                            LastName = "Mozi",
                            Nationality = "Romanina",
                            PositionId = 2,
                            Price = 800000m,
                            Rating = 80,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Tervel",
                            IsDeleted = false,
                            LastName = "Pulev",
                            Nationality = "Bulgarian",
                            PositionId = 2,
                            Price = 600000m,
                            Rating = 60,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Kubrat",
                            IsDeleted = false,
                            LastName = "Pulev",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 800000m,
                            Rating = 80,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Yordanov",
                            Nationality = "Bulgarian",
                            PositionId = 3,
                            Price = 900000m,
                            Rating = 90,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Mladen",
                            IsDeleted = false,
                            LastName = "Stefanov",
                            Nationality = "Bulgarian",
                            PositionId = 4,
                            Price = 760000m,
                            Rating = 76,
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("FM.Data.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Goalkeeper"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Defender"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Midfielder"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Striker"
                        });
                });

            modelBuilder.Entity("FM.Data.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 45000,
                            City = "Sofia",
                            Country = "Bulgaria",
                            Name = "Vasil Levski"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15000,
                            City = "Blagoevgrad",
                            Country = "Bulgaria",
                            Name = "Hristo Botev"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 75000,
                            City = "London",
                            Country = "England",
                            Name = "Wembly"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 75000,
                            City = "Madrid",
                            Country = "Spain",
                            Name = "Bernabeu"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 90000,
                            City = "Barcelona",
                            Country = "Spain",
                            Name = "Knou Camp"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 50000,
                            City = "Torino",
                            Country = "Italy",
                            Name = "Juventus Stadium"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 65000,
                            City = "Munchen",
                            Country = "Germany",
                            Name = "Alianz Arena"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 60000,
                            City = "Instambul",
                            Country = "Turkey",
                            Name = "Ataturk"
                        });
                });

            modelBuilder.Entity("FM.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Budget");

                    b.Property<string>("City")
                        .HasMaxLength(30);

                    b.Property<string>("Country")
                        .HasMaxLength(30);

                    b.Property<int>("GoalDifference");

                    b.Property<int>("GoalsConcede");

                    b.Property<int>("GoalsScored");

                    b.Property<int?>("LeagueId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<string>("Owner")
                        .HasMaxLength(30);

                    b.Property<int>("Points");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 5000000m,
                            City = "Sofia",
                            Country = "Bulgaria",
                            GoalDifference = 0,
                            GoalsConcede = 0,
                            GoalsScored = 0,
                            LeagueId = 1,
                            Name = "Cunami",
                            Owner = "Hristo Konov",
                            Points = 0
                        },
                        new
                        {
                            Id = 2,
                            Budget = 5000000m,
                            City = "Stara Zagora",
                            Country = "Bulgaria",
                            GoalDifference = 0,
                            GoalsConcede = 0,
                            GoalsScored = 0,
                            LeagueId = 1,
                            Name = "Athletic SMU",
                            Owner = "Petar Botev",
                            Points = 0
                        },
                        new
                        {
                            Id = 3,
                            Budget = 5000000m,
                            City = "Blagoevgrad",
                            Country = "Bulgaria",
                            GoalDifference = 0,
                            GoalsConcede = 0,
                            GoalsScored = 0,
                            LeagueId = 1,
                            Name = "Pirin",
                            Owner = "Dimitar Georgiev",
                            Points = 0
                        },
                        new
                        {
                            Id = 4,
                            Budget = 5000000m,
                            City = "Sofia",
                            Country = "Bulgaria",
                            GoalDifference = 0,
                            GoalsConcede = 0,
                            GoalsScored = 0,
                            LeagueId = 1,
                            Name = "Levski",
                            Owner = "Nasko Sirakov",
                            Points = 0
                        },
                        new
                        {
                            Id = 5,
                            Budget = 5000000m,
                            City = "Sofia",
                            Country = "Bulgaria",
                            GoalDifference = 0,
                            GoalsConcede = 0,
                            GoalsScored = 0,
                            LeagueId = 1,
                            Name = "CSKA",
                            Owner = "Hristo Stoichkov",
                            Points = 0
                        },
                        new
                        {
                            Id = 6,
                            Budget = 5000000m,
                            City = "Razgrad",
                            Country = "Bulgaria",
                            GoalDifference = 0,
                            GoalsConcede = 0,
                            GoalsScored = 0,
                            LeagueId = 1,
                            Name = "Ludogorez",
                            Owner = "Kiril Domuschiev",
                            Points = 0
                        });
                });

            modelBuilder.Entity("FM.Data.Models.Manager", b =>
                {
                    b.HasOne("FM.Data.Models.Team", "Team")
                        .WithOne("Manager")
                        .HasForeignKey("FM.Data.Models.Manager", "TeamId");
                });

            modelBuilder.Entity("FM.Data.Models.Match", b =>
                {
                    b.HasOne("FM.Data.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FM.Data.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FM.Data.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FM.Data.Models.Stadium", "Stadium")
                        .WithMany("Match")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FM.Data.Models.Player", b =>
                {
                    b.HasOne("FM.Data.Models.Position", "Position")
                        .WithMany("Player")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FM.Data.Models.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("FM.Data.Models.Team", b =>
                {
                    b.HasOne("FM.Data.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId");
                });
#pragma warning restore 612, 618
        }
    }
}
